branches:
  except:
    - debian

image: Visual Studio 2019

environment:
  generator: Visual Studio 16 2019
  configuration: Debug
  matrix:
    - platform: win32
    - platform: x64

build:
  parallel: true

before_build:
  - git submodule update --init --recursive

build_script:
  - cmd: cmake --version
  - cmd: cmake -G"%generator%" -A"%platform%" -DUSE_WERROR=1 -DBE_VERBOSE=1 -DUSE_PRECOMPILED_HEADER=0 -DBUILD_GAME_NACL=0 -DCMAKE_BUILD_TYPE="%configuration%" -H. -Bbuild
  - cmd: cmake --build build
